version: '3.3'
services:
  localstack:
    image: localstack/localstack:0.12.2
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs,s3,kms
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ~/localstack:/tmp/localstack