version: '3.3'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.9.6
    ports:
      - 4572:4572
      - 4576:4576
    environment:
      - SERVICES=sqs,s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
#      - AWS_ACCESS_KEY_ID=aaa
#      - AWS_SECRET_ACCESS_KEY=aaa
#      - AWS_DEFAULT_OUTPUT=json
    volumes:
      - ./localstack/data:/tmp/localstack/data